GET http://localhost:3000/api

###
POST http://localhost:3000/api/v1/auth/register
Content-Type: application/json

{
    "password": "123456789"
}

###
POST http://localhost:3000/api/v1/auth/login

###
POST http://localhost:3000/api/v1/auth/refresh-token

###
POST http://localhost:3000/api/v1/auth/logout