@baseUrl = http://localhost:3000

### Test API
# @Comment
GET {{baseUrl}}/api

### Register User
POST {{baseUrl}}/api/v1/auth/register
Content-Type: application/json

{
    "first_name": "huy",
    "last_name": "nguyen",
    "email": "huy12345@gmail.com",
    "password": "123456789",
    "repeat_password": "123456789"
}

### Login User
POST {{baseUrl}}/api/v1/auth/login
Content-Type: application/json

{
    "email": "huy12345@gmail.com",
    "password": "123456789"
}
### Refresh Token
POST {{baseUrl}}/api/v1/auth/refresh-token
Content-Type: application/json

{
    "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NjA0OTIwMTYsImV4cCI6MTY2MDQ5MjAyNn0.KkwInVXWTDodiPDSZeMDrKc3Ct82WJiTayIihofdoDU"
}

### Logout
POST {{baseUrl}}/api/v1/auth/logout

### Get All Users
GET {{baseUrl}}/api/v1/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmY5MTFmOWM4M2ExZTQ0MWZkNjMyODkiLCJpYXQiOjE2NjA0OTA1MjcsImV4cCI6MTY2MDQ5MDUzN30.nbZF00LljhjdGw1xBQRX_tpAKOHlbXBbvyxtnyQLWWA

### Get One Users
GET {{baseUrl}}/api/v1/users/62f777afaaab891acb028944

### Delete User
DELETE {{baseUrl}}/api/v1/users/62f9102646c6af2f9d3d4c11
